# Generated by Django 2.1.1 on 2018-09-13 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('seeds_num', models.IntegerField()),
                ('size', models.IntegerField()),
                ('details_link', models.CharField(max_length=200)),
                ('seasons', models.CharField(max_length=200)),
                ('last_season', models.IntegerField()),
                ('audio', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('original_name', models.CharField(max_length=200)),
                ('last_episode', models.IntegerField()),
                ('subtitles', models.CharField(max_length=200)),
                ('has_english_subtitles', models.BooleanField(default=False)),
                ('has_english_audio', models.BooleanField(default=False)),
                ('torrent_link', models.CharField(max_length=200)),
                ('id', models.CharField(max_length=32, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovieList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_string', models.CharField(max_length=200)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webui_list.Movie')),
            ],
        ),
    ]
