# Generated by Django 2.1.1 on 2018-09-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webui_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='quality',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
